/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/7FOTnTwur8P
 */
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Input } from "@/components/ui/input";

export function SantasWorkshopSlack() {
  const channels = ["General", "Elves", "Reindeers", "Robot Notifications"];
  const messages = [
    { type: "robot", text: "New toy production started.", time: "10:15 AM" },
    {
      type: "robot",
      text: "Toy production completed successfully.",
      time: "11:30 AM",
    },
    {
      type: "reindeer",
      text: "Delivery completed successfully.",
      time: "12:45 PM",
    },
    // Add more messages as needed
  ];

  return (
    <div key="1" className="flex flex-col h-screen bg-white dark:bg-gray-900">
      <header className="flex items-center justify-between px-6 py-4 border-b border-gray-200 dark:border-gray-700">
        <div className="flex items-center space-x-3">
          <svg
            className=" w-8 h-8 text-red-500 dark:text-red-400"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M5.7 21a2 2 0 0 1-3.5-2l8.6-14a6 6 0 0 1 10.4 6 2 2 0 1 1-3.464-2 2 2 0 1 0-3.464-2Z" />
            <path d="M17.75 7 15 2.1" />
            <path d="M10.9 4.8 13 9" />
            <path d="m7.9 9.7 2 4.4" />
            <path d="M4.9 14.7 7 18.9" />
          </svg>
          <h1 className="text-2xl font-semibold text-gray-900 dark:text-gray-100">
            Santa's Workshop
          </h1>
        </div>
        <Button className="text-sm" variant="outline">
          Logout
        </Button>
      </header>
      <main className="flex flex-1 overflow-hidden">
        <aside className="flex flex-col w-64 border-r border-gray-200 dark:border-gray-700 p-4 overflow-auto">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">
            Channels
          </h2>
          <nav>
            {channels.map((channel, index) => (
              <Link
                key={index}
                className="block py-1 px-3 text-white rounded hover:bg-gray-100 dark:hover:bg-gray-800 "
                href="#"
              >
                {channel}
              </Link>
            ))}
          </nav>
        </aside>
        <section className="flex flex-col flex-1 p-6">
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-4">
            Robot Notifications
          </h2>
          <div className="flex-1 overflow-auto space-y-4">
            <div className="flex flex-col items-start space-x-3">
              {messages.map((message, index) => (
                <div key={index} className="flex items-start space-x-3">
                  {/* Replace the SVG as needed based on message.type */}
                  <svg /* ...SVG props... */>{/* ...SVG paths... */}</svg>
                  <div>
                    <p className="text-sm text-gray-900 dark:text-gray-100">
                      {message.text}
                    </p>
                    <p className="text-xs text-gray-600 dark:text-gray-400">
                      {message.time}
                    </p>
                  </div>
                </div>
              ))}
            </div>
          </div>
          <div className="mt-4 flex items-center space-x-3">
            <Input
              className="flex-1 text-white rounded border border-gray-200 dark:border-gray-700 p-2"
              placeholder="Type a message..."
            />
            <Button className="text-sm bg-teal-100">Send</Button>
          </div>
        </section>
      </main>
    </div>
  );
}
