/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Rj5d9JwjcbT
 */

export function UltimateGuide() {
  return (
    <div className="px-4 py-6 md:px-6 md:py-12 lg:py-16">
      <article className="prose prose-zinc mx-auto max-w-6xl dark:prose-invert">
        <div className="space-y-2 not-prose">
          <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl lg:leading-[3.5rem]">
            The Ultimate Guide to a Spectacular Christmas: Gifts, Decor, and
            Recipes
          </h1>
          <p className="text-zinc-500 dark:text-zinc-400">
            Posted on November 25, 2023
          </p>
        </div>
        <p>
          Christmas is right around the corner, and the festive spirit is in the
          air! It&apos;s time to celebrate with gifts, decorations, and
          mouthwatering recipes.
        </p>
        <figure>
          <img
            alt="Christmas decoration"
            className="aspect-video overflow-hidden rounded-lg object-cover"
            height="340"
            src="/placeholder.svg"
            width="1250"
          />
          <figcaption>
            Beautiful Christmas decorations to inspire you
          </figcaption>
        </figure>
        <div className="my-4">
          <img
            alt="Advertisement"
            className="mx-auto"
            height="90"
            src="/placeholder.svg"
            style={{
              aspectRatio: "728/90",
              objectFit: "cover",
            }}
            width="728"
          />
        </div>
        <h2>Top Christmas Gift Ideas</h2>
        <p>
          Choosing the perfect Christmas gift can be a daunting task. But don't
          worry, we've got you covered with our top Christmas gift ideas.
        </p>
        <h2>Holiday Decorating Tips</h2>
        <p>
          Transform your home into a Christmas wonderland with our holiday
          decorating tips. From Christmas tree decorations to festive table
          settings, we have all the inspiration you need.
        </p>
        <figure>
          <img
            alt="Christmas tree decoration"
            className="aspect-video overflow-hidden rounded-lg object-cover"
            height="340"
            src="/placeholder.svg"
            width="1250"
          />
          <figcaption>Decorate your Christmas tree like a pro!</figcaption>
        </figure>
        <div className="my-4">
          <img
            alt="Advertisement"
            className="mx-auto"
            height="90"
            src="/placeholder.svg"
            style={{
              aspectRatio: "728/90",
              objectFit: "cover",
            }}
            width="728"
          />
        </div>
        <h2>Delicious Christmas Recipes</h2>
        <p>
          Christmas is a time for indulgence, and we've got the best Christmas
          recipes for you to try. From traditional roast turkey to decadent
          desserts, we have something for everyone.
        </p>
      </article>
    </div>
  );
}
