/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/cTTKeM7clIF
 */
import { Input } from "@/components/ui/input";
import Link from "next/link";
import { Button } from "@/components/ui/button";

export function WorkshopLanding() {
  return (
    <div className="flex flex-col min-h-screen bg-gray-50 dark:bg-gray-800">
      <header className="px-6 py-4 flex justify-between items-center bg-red-600 dark:bg-red-800 text-white">
        <div className="flex items-center">
          <svg
            className=" h-10 w-10"
            fill="none"
            height="24"
            stroke="currentColor"
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            viewBox="0 0 24 24"
            width="24"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M6 13.87A4 4 0 0 1 7.41 6a5.11 5.11 0 0 1 1.05-1.54 5 5 0 0 1 7.08 0A5.11 5.11 0 0 1 16.59 6 4 4 0 0 1 18 13.87V21H6Z" />
            <line x1="6" x2="18" y1="17" y2="17" />
          </svg>
          <span className="ml-3 text-2xl font-bold">XmasGPT</span>
        </div>
        <Input
          className="w-1/2 px-3 py-2 rounded-md text-gray-900 dark:text-gray-100"
          placeholder="Search..."
          type="search"
        />
        <div className="flex space-x-6">
          <Link className="text-lg font-semibold" href="#">
            Login
          </Link>
          <Button
            className="text-lg font-semibold px-4 py-2 rounded-md bg-white dark:bg-gray-200 text-red-600 dark:text-red-400"
            href="/signup"
          >
            Sign Up
          </Button>
        </div>
      </header>
      <section
        className="flex flex-col items-center justify-center w-full h-[60vh] bg-center bg-cover text-white"
        style={{
          backgroundImage: "url('/santas-workshop.jpg')",
        }}
      >
        <h1 className="text-5xl font-bold tracking-wide">
          Welcome to Santa&apos;s Workshop
        </h1>
        <p className="mt-3 text-2xl">Making every wish come true</p>
        <Button className="mt-6 px-8 py-3 text-2xl font-bold rounded-md bg-white text-red-600">
          Make a Wish
        </Button>
      </section>
      <section className="p-6">
        <h2 className="text-3xl font-bold text-center text-gray-800 dark:text-gray-100">
          Santa&apos;s Workshop Features
        </h2>
        <p className="mt-4 text-lg text-center text-gray-600 dark:text-gray-400">
          At Santa&apos;s workshop, we work all year to bring joy to children
          worldwide. Discover our workshop&apos;s features:
        </p>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8 mt-10">
          <div className="flex flex-col items-center space-y-4 p-6 bg-white dark:bg-gray-700 rounded-md shadow-md">
            <svg
              className=" h-10 w-10 text-red-600 dark:text-red-400"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <polyline points="20 12 20 22 4 22 4 12" />
              <rect height="5" width="20" x="2" y="7" />
              <line x1="12" x2="12" y1="22" y2="7" />
              <path d="M12 7H7.5a2.5 2.5 0 0 1 0-5C11 2 12 7 12 7z" />
              <path d="M12 7h4.5a2.5 2.5 0 0 0 0-5C13 2 12 7 12 7z" />
            </svg>
            <p className="text-center text-lg font-medium text-gray-800 dark:text-gray-100">
              Thousands of gifts produced daily
            </p>
          </div>
          <div className="flex flex-col items-center space-y-4 p-6 bg-white dark:bg-gray-700 rounded-md shadow-md">
            <svg
              className=" h-10 w-10 text-red-600 dark:text-red-400"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M5.7 21a2 2 0 0 1-3.5-2l8.6-14a6 6 0 0 1 10.4 6 2 2 0 1 1-3.464-2 2 2 0 1 0-3.464-2Z" />
              <path d="M17.75 7 15 2.1" />
              <path d="M10.9 4.8 13 9" />
              <path d="m7.9 9.7 2 4.4" />
              <path d="M4.9 14.7 7 18.9" />
            </svg>
            <p className="text-center text-lg font-medium text-gray-800 dark:text-gray-100">
              Fast delivery with Santa&apos;s reindeers
            </p>
          </div>
          <div className="flex flex-col items-center space-y-4 p-6 bg-white dark:bg-gray-700 rounded-md shadow-md">
            <svg
              className=" h-10 w-10 text-red-600 dark:text-red-400"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="M12 2a10 10 0 1 0 10 10 4 4 0 0 1-5-5 4 4 0 0 1-5-5" />
              <path d="M8.5 8.5v.01" />
              <path d="M16 15.5v.01" />
              <path d="M12 12v.01" />
              <path d="M11 17v.01" />
              <path d="M7 14v.01" />
            </svg>
            <p className="text-center text-lg font-medium text-gray-800 dark:text-gray-100">
              Delicious cookies for every good child
            </p>
          </div>
          <div className="flex flex-col items-center space-y-4 p-6 bg-white dark:bg-gray-700 rounded-md shadow-md">
            <svg
              className=" h-10 w-10 text-red-600 dark:text-red-400"
              fill="none"
              height="24"
              stroke="currentColor"
              strokeLinecap="round"
              strokeLinejoin="round"
              strokeWidth="2"
              viewBox="0 0 24 24"
              width="24"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path d="m2 7 4.41-4.41A2 2 0 0 1 7.83 2h8.34a2 2 0 0 1 1.42.59L22 7" />
              <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
              <path d="M15 22v-4a2 2 0 0 0-2-2h-2a2 2 0 0 0-2 2v4" />
              <path d="M2 7h20" />
              <path d="M22 7v3a2 2 0 0 1-2 2v0a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 16 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 12 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 8 12a2.7 2.7 0 0 1-1.59-.63.7.7 0 0 0-.82 0A2.7 2.7 0 0 1 4 12v0a2 2 0 0 1-2-2V7" />
            </svg>
            <p className="text-center text-lg font-medium text-gray-800 dark:text-gray-100">
              Festive stockings filled with surprises
            </p>
          </div>
        </div>
      </section>
      <footer className="px-6 py-4 flex justify-around bg-red-600 dark:bg-red-800 text-white">
        <Link className="text-lg font-semibold" href="#">
          Terms of Service
        </Link>
        <Link className="text-lg font-semibold" href="#">
          Privacy Policy
        </Link>
        <Link className="text-lg font-semibold" href="#">
          Contact Us
        </Link>
      </footer>
    </div>
  );
}
